name: Vite Bundle Stats

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  bundle-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Improve npm network resilience
        run: |
          npm config set fetch-retries 5
          npm config set fetch-retry-factor 2
          npm config set fetch-retry-mintimeout 20000
          npm config set fetch-retry-maxtimeout 120000

      - name: Install dependencies (with retry)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --fund=false || (npm cache clean --force && npm ci --no-audit --fund=false)
          else
            npm i --no-audit --fund=false || (npm cache clean --force && npm i --no-audit --fund=false)
          fi

      - name: Build frontend (Vite)
        run: npm run build

      - name: Compute bundle stats
        id: stats
        run: |
          DIST_DIR="dist/assets"
          echo "DIST_DIR=${DIST_DIR}" >> $GITHUB_OUTPUT
          echo "# Bundle Stats" > bundle-stats.md
          if [ -d "$DIST_DIR" ]; then
            echo "\nTotal dist size:" >> bundle-stats.md
            du -sh dist | sed 's/^/- /' >> bundle-stats.md

            echo "\nTop 10 largest assets:" >> bundle-stats.md
            # List largest files with gzip sizes
            {
              echo "filename,size,gzip"
              find "$DIST_DIR" -type f -printf "%p,%s\n" | sort -t, -k2 -nr | head -n 10 | while IFS=, read -r f s; do
                gz=$(gzip -c "$f" | wc -c)
                echo "$f,$s,$gz"
              done
            } > bundle-stats.csv

            # Format as markdown table
            {
              echo "\n| File | Size (bytes) | Gzip (bytes) |"
              echo "|---|---:|---:|"
              tail -n +2 bundle-stats.csv | while IFS=, read -r f s gz; do
                echo "| ${f#dist/} | $s | $gz |"
              done
            } >> bundle-stats.md
          else
            echo "\nNo dist/assets found. Did the build run?" >> bundle-stats.md
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-stats
          path: |
            bundle-stats.md
            bundle-stats.csv
          if-no-files-found: warn

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const body = fs.readFileSync('bundle-stats.md', 'utf8');
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;

            // Find existing bot comment
            const { data: comments } = await github.rest.issues.listComments({ owner, repo, issue_number });
            const marker = 'Bundle Stats';
            const botComment = comments.find(c => c.user.type === 'Bot' && c.body && c.body.includes('# ' + marker));
            if (botComment) {
              await github.rest.issues.updateComment({ owner, repo, comment_id: botComment.id, body });
            } else {
              await github.rest.issues.createComment({ owner, repo, issue_number, body });
            }
