name: Compatibility Matrix
on:
  pull_request:

jobs:
  node-matrix:
    name: Node ${{ matrix.node }} build/test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies (root)
        run: npm ci

      - name: Install dependencies (server)
        run: |
          cd server
          npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Frontend unit tests
        run: npm test -- --run

      - name: Backend unit tests
        run: |
          cd server
          npm test -- --run
